### ISSUE TITLE
Works for 1.8.1 wrapper, However

### ISSUE THREAD

**Issue by WASasquatch** [McCraftaholics/Bukkit-WarpPortals#29]
Portals only face one direction. So all your portals can only face one direction.

**Comment by awendland** [comment]
This appears to be a Spigot 1.8 issue concerning the auto-orientation of PORTAL blocks

**Comment by awendland** [comment]
This has been fixed by https://github.com/McCraftaholics/Bukkit-WarpPortals/commit/d10633b8d5010dcb08a8bb3aa0df9faf5d10db31. Custom block data type is allowed now. If portals are facing the wrong direction they can be corrected by changing the WarpPortal material to PORTAL:2, which fixes the orientation.

**Comment by WASasquatch** [comment]
Nice work! Thank you.

**Comment by awendland** [comment]
For documentation sake:

The command `/wppm PortalName PORTAL:2` should be run to correct broken portals.

**Comment by WASasquatch** [comment]
Oh nice! Was literally about to just make new ones.
